/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pmi.prog2;

/**
 *
 * @author Jere
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        Hipo = new javax.swing.JPanel();
        mLabel1 = new javax.swing.JLabel();
        mLabel2 = new javax.swing.JLabel();
        mLabel3 = new javax.swing.JLabel();
        mLabel4 = new javax.swing.JLabel();
        mLabel5 = new javax.swing.JLabel();
        mjLabel6 = new javax.swing.JLabel();
        mTextField1 = new javax.swing.JTextField();
        mTextField2 = new javax.swing.JTextField();
        mTextField3 = new javax.swing.JTextField();
        mTextField4 = new javax.swing.JTextField();
        mTextField5 = new javax.swing.JTextField();
        mLabel7 = new javax.swing.JLabel();
        mTextField6 = new javax.swing.JTextField();
        mLabel8 = new javax.swing.JLabel();
        mLabel9 = new javax.swing.JLabel();
        mTextField7 = new javax.swing.JTextField();
        mTextField8 = new javax.swing.JTextField();
        mRadioButton1 = new javax.swing.JRadioButton();
        mRadioButton2 = new javax.swing.JRadioButton();
        mSeparator1 = new javax.swing.JSeparator();
        mSeparator2 = new javax.swing.JSeparator();
        Cuadro = new javax.swing.JPanel();
        mLabel10 = new javax.swing.JLabel();
        mSeparator3c = new javax.swing.JSeparator();
        mPanel1 = new javax.swing.JPanel();
        mScrollPane2 = new javax.swing.JScrollPane();
        mTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        mLabel1.setText("Agregar propiedad");

        mLabel2.setText("Direccion:");

        mLabel3.setText("Tasacion:");

        mLabel4.setText("Cantidad de Ambientes:");

        mLabel5.setText("Metros Cuadrados Cubiertos:");

        mjLabel6.setText("Metros Cuadrados Totales:");

        mTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mTextField5ActionPerformed(evt);
            }
        });

        mLabel7.setText("Antiguedad");

        mTextField6.setText("dd/mm/aaaa");

        mLabel8.setText("Piso");

        mLabel9.setText("Identificacion");

        mTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mTextField7ActionPerformed(evt);
            }
        });

        mRadioButton1.setLabel("Casa");

        mRadioButton2.setLabel("Depto");

        mSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        mSeparator2.setToolTipText("");

        javax.swing.GroupLayout HipoLayout = new javax.swing.GroupLayout(Hipo);
        Hipo.setLayout(HipoLayout);
        HipoLayout.setHorizontalGroup(
            HipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HipoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HipoLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(HipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(HipoLayout.createSequentialGroup()
                                .addComponent(mLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(HipoLayout.createSequentialGroup()
                                .addGroup(HipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(HipoLayout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addGroup(HipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(HipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(mLabel5)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(mLabel3)
                                                    .addComponent(mLabel2)))
                                            .addGroup(HipoLayout.createSequentialGroup()
                                                .addComponent(mLabel4)
                                                .addGap(1, 1, 1))
                                            .addComponent(mjLabel6)
                                            .addComponent(mTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addGroup(HipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mTextField1)
                                            .addComponent(mTextField2)
                                            .addComponent(mTextField3)
                                            .addComponent(mTextField4)
                                            .addComponent(mTextField5)))
                                    .addGroup(HipoLayout.createSequentialGroup()
                                        .addComponent(mRadioButton1)
                                        .addGap(114, 114, 114)
                                        .addComponent(mSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(HipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mRadioButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(mLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18)
                                        .addComponent(mTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                                    .addGroup(HipoLayout.createSequentialGroup()
                                        .addComponent(mLabel7)
                                        .addGap(132, 132, 132)
                                        .addComponent(mLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(mTextField8)))
                                .addGap(58, 58, 58))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HipoLayout.createSequentialGroup()
                        .addComponent(mSeparator1)
                        .addContainerGap())))
        );
        HipoLayout.setVerticalGroup(
            HipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HipoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(mLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(HipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mLabel2)
                    .addComponent(mTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mLabel3))
                .addGap(18, 18, 18)
                .addGroup(HipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mLabel4)
                    .addComponent(mTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(HipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mLabel5)
                    .addComponent(mTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(HipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mjLabel6)
                    .addComponent(mTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(HipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HipoLayout.createSequentialGroup()
                        .addGroup(HipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mRadioButton1)
                            .addComponent(mRadioButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(HipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mLabel8)
                            .addComponent(mTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(HipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mLabel9)
                            .addComponent(mLabel7)
                            .addComponent(mTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(mSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        mRadioButton2.getAccessibleContext().setAccessibleParent(mRadioButton1);

        mLabel10.setText("Lista de personas con hipotecas activas");

        javax.swing.GroupLayout mPanel1Layout = new javax.swing.GroupLayout(mPanel1);
        mPanel1.setLayout(mPanel1Layout);
        mPanel1Layout.setHorizontalGroup(
            mPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        mPanel1Layout.setVerticalGroup(
            mPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );

        mTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        mScrollPane2.setViewportView(mTable1);

        javax.swing.GroupLayout CuadroLayout = new javax.swing.GroupLayout(Cuadro);
        Cuadro.setLayout(CuadroLayout);
        CuadroLayout.setHorizontalGroup(
            CuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuadroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mLabel10)
                    .addComponent(mSeparator3c, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CuadroLayout.createSequentialGroup()
                        .addComponent(mScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CuadroLayout.setVerticalGroup(
            CuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuadroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mSeparator3c, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(CuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CuadroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CuadroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(Hipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGap(258, 258, 258)
                    .addComponent(Cuadro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(259, Short.MAX_VALUE)))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(Hipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGap(145, 145, 145)
                    .addComponent(Cuadro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(145, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mTextField5ActionPerformed

    private void mTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mTextField7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cuadro;
    private javax.swing.JPanel Hipo;
    private javax.swing.JLabel mLabel1;
    private javax.swing.JLabel mLabel10;
    private javax.swing.JLabel mLabel2;
    private javax.swing.JLabel mLabel3;
    private javax.swing.JLabel mLabel4;
    private javax.swing.JLabel mLabel5;
    private javax.swing.JLabel mLabel7;
    private javax.swing.JLabel mLabel8;
    private javax.swing.JLabel mLabel9;
    private javax.swing.JPanel mPanel1;
    private javax.swing.JRadioButton mRadioButton1;
    private javax.swing.JRadioButton mRadioButton2;
    private javax.swing.JScrollPane mScrollPane2;
    private javax.swing.JSeparator mSeparator1;
    private javax.swing.JSeparator mSeparator2;
    private javax.swing.JSeparator mSeparator3c;
    private javax.swing.JTable mTable1;
    private javax.swing.JTextField mTextField1;
    private javax.swing.JTextField mTextField2;
    private javax.swing.JTextField mTextField3;
    private javax.swing.JTextField mTextField4;
    private javax.swing.JTextField mTextField5;
    private javax.swing.JTextField mTextField6;
    private javax.swing.JTextField mTextField7;
    private javax.swing.JTextField mTextField8;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel mjLabel6;
    // End of variables declaration//GEN-END:variables
}
